# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel-0.11.1-installer-linux-x86_64.sh
      - run: chmod +x bazel-0.11.1-installer-linux-x86_64.sh
      - run: ./bazel-0.11.1-installer-linux-x86_64.sh --user
      - run: ~/bin/bazel build //mcts:mcts_main //dist:dist_zero_model_server
